'first_tasks'
Drop777/node_movies-api pull request #1
Opened 2019-11-13 12:51 UTC by Drop777

2019-11-14 08:44 UTC, YuriiHoliuk requested changes
There are no first 4 tasks in PR changes

2019-11-14 08:44 UTC, YuriiHoliuk commented on src/server.js
> +const jsonParser = bodyParser.json();
there are `express.json()` middleware, no need to install separate library

2019-11-14 08:44 UTC, YuriiHoliuk commented on src/server.js
> +  dataWithNewFilm = [...movies, newMovie];
will be great to add some empty lines

2019-11-14 08:44 UTC, YuriiHoliuk commented on src/server.js
> +  const movies = JSON.parse(fs.readFileSync(JSON_PATH));
Do not use Sync methods, your server will be slow

2019-11-14 08:44 UTC, YuriiHoliuk commented on src/server.js
> +  dataWithNewFilm = [...movies, newMovie];
Where is variable declaration?
`movie` -> `film` -> `data`??🤔

2019-11-14 08:44 UTC, YuriiHoliuk commented on src/server.js
> +        return ({
unneeded parentethes

2019-11-14 08:44 UTC, YuriiHoliuk commented on src/server.js
> +  const movieWithChange = JSON.parse(fs.readFileSync(JSON_PATH))
no Sync

2019-11-14 08:44 UTC, YuriiHoliuk commented on src/server.js
> +      res.json(newDataForMovie);
Here, you should send object with id

2019-11-14 08:44 UTC, YuriiHoliuk commented on src/server.js
> +      res.json(newDataForMovie);
Here, you should send object with id

2019-11-14 08:44 UTC, YuriiHoliuk commented on src/server.js
> +  const movieWithChange = JSON.parse(fs.readFileSync(JSON_PATH))
movieWithChange - not the best name

2019-11-14 08:44 UTC, YuriiHoliuk commented on src/server.js
> +        return ({
will be better to use ternary here

2019-11-14 09:12 UTC, YuriiHoliuk commented on src/server.js
> +app.put('/movies/:id', jsonParser, (req, res) => {
```suggestion
app.put('/movies/:id', express.json(), (req, res) => {
```

2019-11-14 20:06 UTC, danheim commented
Зачем парсить каждый метод отдельно, если можно `app.use(express.json())`?

2019-11-15 10:04 UTC, YuriiHoliuk approved these changes
Супер, круто зробив!

2019-11-17 21:53 UTC, merged